# Generated by Django 5.0.2 on 2024-03-04 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0002_remove_category_id_alter_category_name"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="categories",
            field=models.ManyToManyField(related_name="products", to="categories.category"),
        ),
    ]
