# Generated by Django 5.0.2 on 2024-03-04 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0001_initial"),
        ("products", "0002_product_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="company.company",
            ),
        ),
    ]
